import { sql } from 'drizzle-orm'
import { pgTable, uuid, text, timestamp, integer, pgEnum, index, unique } from 'drizzle-orm/pg-core'

export const chatRole = pgEnum('chat_role', ['user', 'assistant'])

export type ChatRole = (typeof chatRole.enumValues)[number]

/**
 * chat_threads — one saved assistant conversation. The id is generated by
 * the client. The title is AES-256-GCM (apps/server's vault.ts); the
 * plaintext title is never a column.
 */
export const chatThreads = pgTable(
  'chat_threads',
  {
    id: uuid('id').primaryKey(),
    tenantId: uuid('tenant_id').notNull(),
    titleCiphertext: text('title_ciphertext').notNull(),
    titleNonce: text('title_nonce').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index('chat_threads_tenant_updated_idx').on(table.tenantId, sql`${table.updatedAt} desc`)],
)

/** chat_messages — the turns of a thread in seq order; content is encrypted like the title. */
export const chatMessages = pgTable(
  'chat_messages',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    threadId: uuid('thread_id').notNull().references(() => chatThreads.id, { onDelete: 'cascade' }),
    seq: integer('seq').notNull(),
    role: chatRole('role').notNull(),
    contentCiphertext: text('content_ciphertext').notNull(),
    contentNonce: text('content_nonce').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [unique('chat_messages_thread_seq_unique').on(table.threadId, table.seq)],
)
