-- SOURCE OF TRUTH: seed data for the system categorization taxonomy (S1-1).
-- WHAT: 50 of Plaid's 104 PFCv2 detailed categories, across all 16 primaries.
-- WHY: tenant_id NULL / is_system true = shared base taxonomy every tenant
-- gets for free; user categories layer on top with tenant_id set.
-- WHERE: seed DATA only. Table shape lives in schema.ts / 0003_vengeful_vampiro.sql.

INSERT INTO "categories" ("tenant_id", "primary", "detailed", "label", "is_system") VALUES
  (NULL, 'INCOME', 'INCOME_WAGES', 'Salary & Wages', true),
  (NULL, 'INCOME', 'INCOME_INTEREST_EARNED', 'Interest Earned', true),
  (NULL, 'INCOME', 'INCOME_TAX_REFUND', 'Tax Refund', true),
  (NULL, 'INCOME', 'INCOME_OTHER_INCOME', 'Other Income', true),
  (NULL, 'TRANSFER_IN', 'TRANSFER_IN_DEPOSIT', 'Deposit', true),
  (NULL, 'TRANSFER_IN', 'TRANSFER_IN_ACCOUNT_TRANSFER', 'Transfer In (Account)', true),
  (NULL, 'TRANSFER_IN', 'TRANSFER_IN_CASH_ADVANCES_AND_LOANS', 'Loan/Advance Received', true),
  (NULL, 'TRANSFER_OUT', 'TRANSFER_OUT_WITHDRAWAL', 'Withdrawal', true),
  (NULL, 'TRANSFER_OUT', 'TRANSFER_OUT_ACCOUNT_TRANSFER', 'Transfer Out (Account)', true),
  (NULL, 'TRANSFER_OUT', 'TRANSFER_OUT_SAVINGS', 'Transfer to Savings', true),
  (NULL, 'LOAN_PAYMENTS', 'LOAN_PAYMENTS_CREDIT_CARD_PAYMENT', 'Credit Card Payment', true),
  (NULL, 'LOAN_PAYMENTS', 'LOAN_PAYMENTS_PERSONAL_LOAN_PAYMENT', 'Personal Loan Payment', true),
  (NULL, 'LOAN_PAYMENTS', 'LOAN_PAYMENTS_OTHER_PAYMENT', 'Other Loan Payment', true),
  (NULL, 'BANK_FEES', 'BANK_FEES_ATM_FEES', 'ATM Fees', true),
  (NULL, 'BANK_FEES', 'BANK_FEES_OTHER_BANK_FEES', 'Other Bank Fees', true),
  (NULL, 'ENTERTAINMENT', 'ENTERTAINMENT_TV_AND_MOVIES', 'TV & Movies', true),
  (NULL, 'ENTERTAINMENT', 'ENTERTAINMENT_VIDEO_GAMES', 'Video Games', true),
  (NULL, 'ENTERTAINMENT', 'ENTERTAINMENT_OTHER_ENTERTAINMENT', 'Other Entertainment', true),
  (NULL, 'FOOD_AND_DRINK', 'FOOD_AND_DRINK_GROCERIES', 'Groceries', true),
  (NULL, 'FOOD_AND_DRINK', 'FOOD_AND_DRINK_RESTAURANT', 'Restaurant', true),
  (NULL, 'FOOD_AND_DRINK', 'FOOD_AND_DRINK_FAST_FOOD', 'Fast Food', true),
  (NULL, 'FOOD_AND_DRINK', 'FOOD_AND_DRINK_COFFEE', 'Coffee', true),
  (NULL, 'GENERAL_MERCHANDISE', 'GENERAL_MERCHANDISE_ONLINE_MARKETPLACES', 'Online Marketplaces', true),
  (NULL, 'GENERAL_MERCHANDISE', 'GENERAL_MERCHANDISE_CLOTHING_AND_ACCESSORIES', 'Clothing & Accessories', true),
  (NULL, 'GENERAL_MERCHANDISE', 'GENERAL_MERCHANDISE_ELECTRONICS', 'Electronics', true),
  (NULL, 'GENERAL_MERCHANDISE', 'GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE', 'Other Merchandise', true),
  (NULL, 'HOME_IMPROVEMENT', 'HOME_IMPROVEMENT_OTHER_HOME_IMPROVEMENT', 'Home Improvement', true),
  (NULL, 'MEDICAL', 'MEDICAL_PHARMACIES_AND_SUPPLEMENTS', 'Pharmacy & Supplements', true),
  (NULL, 'MEDICAL', 'MEDICAL_PRIMARY_CARE', 'Primary Care', true),
  (NULL, 'MEDICAL', 'MEDICAL_OTHER_MEDICAL', 'Other Medical', true),
  (NULL, 'PERSONAL_CARE', 'PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS', 'Gym & Fitness', true),
  (NULL, 'PERSONAL_CARE', 'PERSONAL_CARE_HAIR_AND_BEAUTY', 'Hair & Beauty', true),
  (NULL, 'PERSONAL_CARE', 'PERSONAL_CARE_OTHER_PERSONAL_CARE', 'Other Personal Care', true),
  (NULL, 'GENERAL_SERVICES', 'GENERAL_SERVICES_EDUCATION', 'Education', true),
  (NULL, 'GENERAL_SERVICES', 'GENERAL_SERVICES_INSURANCE', 'Insurance', true),
  (NULL, 'GENERAL_SERVICES', 'GENERAL_SERVICES_OTHER_GENERAL_SERVICES', 'Other Services', true),
  (NULL, 'GOVERNMENT_AND_NON_PROFIT', 'GOVERNMENT_AND_NON_PROFIT_TAX_PAYMENT', 'Tax Payment', true),
  (NULL, 'GOVERNMENT_AND_NON_PROFIT', 'GOVERNMENT_AND_NON_PROFIT_DONATIONS', 'Donations', true),
  (NULL, 'TRANSPORTATION', 'TRANSPORTATION_GAS', 'Fuel', true),
  (NULL, 'TRANSPORTATION', 'TRANSPORTATION_TAXIS_AND_RIDE_SHARES', 'Taxis & Ride Shares', true),
  (NULL, 'TRANSPORTATION', 'TRANSPORTATION_PUBLIC_TRANSIT', 'Public Transit', true),
  (NULL, 'TRANSPORTATION', 'TRANSPORTATION_OTHER_TRANSPORTATION', 'Other Transportation', true),
  (NULL, 'TRAVEL', 'TRAVEL_FLIGHTS', 'Flights', true),
  (NULL, 'TRAVEL', 'TRAVEL_LODGING', 'Lodging', true),
  (NULL, 'TRAVEL', 'TRAVEL_OTHER_TRAVEL', 'Other Travel', true),
  (NULL, 'RENT_AND_UTILITIES', 'RENT_AND_UTILITIES_RENT', 'Rent', true),
  (NULL, 'RENT_AND_UTILITIES', 'RENT_AND_UTILITIES_GAS_AND_ELECTRICITY', 'Electricity & Gas', true),
  (NULL, 'RENT_AND_UTILITIES', 'RENT_AND_UTILITIES_INTERNET_AND_CABLE', 'Internet & Cable', true),
  (NULL, 'RENT_AND_UTILITIES', 'RENT_AND_UTILITIES_TELEPHONE', 'Phone Bill', true),
  (NULL, 'RENT_AND_UTILITIES', 'RENT_AND_UTILITIES_WATER', 'Water Bill', true);
